theme: jekyll-theme-minimal
title: [Gsoc Revisiting Physical Sun and Sky Model]
description: [This project will improve the current Appleseed's implementation of physical sun and sky models. Fixing the current blue tint present on Appleseed implementation and adding several new features. Such as, a solar disk, ability to configure the Sun with a geographic location, a date and a time and allow users to change atmosphere parameters.]
